 2019-01-24 11:47:43,483 [P1212/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.13.1 application starting on DESKTOP-4B6R4DT
 2019-01-24 11:47:43,528 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2019-01-24 11:47:43,612 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 83ms)
 2019-01-24 11:47:43,772 [P1212/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2019-01-24 11:47:43,774 [P1212/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2019-01-24 11:47:43,777 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-01-24 11:47:44,539 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 761ms)
 2019-01-24 11:47:44,539 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2019-01-24 11:47:44,556 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 16ms)
 2019-01-24 11:47:44,594 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-01-24 11:47:44,595 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-01-24 11:47:44,595 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2019-01-24 11:47:44,609 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 13ms)
 2019-01-24 11:47:44,610 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-01-24 11:47:44,610 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-01-24 11:47:44,610 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2019-01-24 11:47:44,621 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 10ms)
 2019-01-24 11:47:44,644 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-01-24 11:47:44,644 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-01-24 11:47:44,645 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2019-01-24 11:47:44,658 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 13ms)
 2019-01-24 11:47:44,659 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-01-24 11:47:44,660 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-01-24 11:47:44,660 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2019-01-24 11:47:44,674 [P1212/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 14ms)
 2019-01-24 11:47:50,763 [P1212/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\i7 vPro\Documents\Trabajo\WebApplication5\WebApplication5\App_Data\Umbraco.sdf ]
   en System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   en System.Data.SqlServerCe.SqlCeConnection.Open()
   en Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2019-01-24 11:47:50,770 [P1212/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-01-24 11:47:51,121 [P1212/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\i7 vPro\Documents\Trabajo\WebApplication5\WebApplication5\App_Data\Umbraco.sdf ]
   en System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   en System.Data.SqlServerCe.SqlCeConnection.Open()
   en Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2019-01-24 11:47:51,122 [P1212/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-01-24 11:47:52,231 [P1212/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\i7 vPro\Documents\Trabajo\WebApplication5\WebApplication5\App_Data\Umbraco.sdf ]
   en System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   en System.Data.SqlServerCe.SqlCeConnection.Open()
   en Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2019-01-24 11:47:52,233 [P1212/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-01-24 11:47:53,319 [P1212/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\i7 vPro\Documents\Trabajo\WebApplication5\WebApplication5\App_Data\Umbraco.sdf ]
   en System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   en System.Data.SqlServerCe.SqlCeConnection.Open()
   en Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2019-01-24 11:47:53,320 [P1212/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-01-24 11:47:54,363 [P1212/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\i7 vPro\Documents\Trabajo\WebApplication5\WebApplication5\App_Data\Umbraco.sdf ]
   en System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   en System.Data.SqlServerCe.SqlCeConnection.Open()
   en Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2019-01-24 11:47:54,363 [P1212/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-01-24 11:47:55,429 [P1212/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\i7 vPro\Documents\Trabajo\WebApplication5\WebApplication5\App_Data\Umbraco.sdf ]
   en System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   en System.Data.SqlServerCe.SqlCeConnection.Open()
   en Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2019-01-24 11:47:55,431 [P1212/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-01-24 11:47:56,521 [P1212/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: |DataDirectory|\Umbraco.sdf. Exception: System.Data.SqlServerCe.SqlCeException (0x80004005): The database file cannot be found. Check the path to the database. [ Data Source = C:\Users\i7 vPro\Documents\Trabajo\WebApplication5\WebApplication5\App_Data\Umbraco.sdf ]
   en System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
   en System.Data.SqlServerCe.SqlCeConnection.Open()
   en Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
 2019-01-24 11:47:56,521 [P1212/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-01-24 11:47:57,138 [P1212/D2/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but Umbraco cannot connect to the database.
   en Umbraco.Core.CoreBootManager.EnsureDatabaseConnection()
   en Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   en Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   en Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   en Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)
 2019-01-24 11:48:08,384 [P1212/D2/T3] INFO  Umbraco.Core.MainDom - Stopping...
 2019-01-24 11:48:08,386 [P1212/D2/T3] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2019-01-24 11:48:08,889 [P1212/D2/T3] INFO  Umbraco.Web.ExamineStartup - Complete (took 503ms)
 2019-01-24 11:48:08,890 [P1212/D2/T3] INFO  Umbraco.Core.MainDom - Released MainDom.
 2019-01-24 11:48:39,006 [P1212/D2/T9] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: InitializationError

_shutDownMessage=Initialization Error
HostingEnvironment initiated shutdown
HostingEnvironment originó el cierre

_shutDownStack=   en System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   en System.Environment.get_StackTrace()
   en System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   en System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   en System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   en System.Web.HttpRuntime.AppDomainShutdownTimerCallback(Object state)
   en System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.TimerQueueTimer.CallCallback()
   en System.Threading.TimerQueueTimer.Fire()
   en System.Threading.TimerQueue.FireNextTimers()
   en System.Threading.TimerQueue.AppDomainTimerCallback()
